### ISSUE TITLE
llightConverter not working on my end

### ISSUE THREAD

**Issue by FusionDragonoid** [blueskythlikesclouds/SkythTools#12]
When I try to convert a "_llight.orc" file with the llightConverter tool, it only displays a command prompt, and after a few minutes it closes and, well, nothing happens. Not even any error codes whatsoever. In the past, the tool worked as intended, so I'm unsure as to why this is happening.

When I double-click on the ".exe" for the tool by itself, it displays the usual text:
![image](https://github.com/blueskythlikesclouds/SkythTools/assets/70831051/0f25029b-0b40-41f7-94aa-2aceb8f8d646)

But with a "_llight.orc" file being dragged into the ".exe", the issue I described occurs.

I'm unsure if this is a compatibility issue or not, or if I'm missing anything that's required for the tool to work. But in case it helps, I'm currently running Windows 11 Home, version 23H2.

**Comment by blueskythlikesclouds** [comment]
Are you trying to convert SCU files or something? These are little endian so they won't work with this tool.

**Comment by FusionDragonoid** [comment]
The "dvd_builder_image" assets in SCU's files (which contain the cutscene assets), yea. Wasn't aware the llight files in them were different--

Still had the retail Colors Wii assets on hand so thankfully I was able to solve this issue.
