### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by Auxy6858** [blueskythlikesclouds/SkythTools#13]
Do you still have the source code for any of these programs?

**Comment by blueskythlikesclouds** [comment]
Is there one you are particularly interested in? I can try to dig it up.

**Comment by Auxy6858** [comment]
Yes, the ar0packer and unpacker.

**Comment by blueskythlikesclouds** [comment]
Oh, these just use [libgens-sonicglvl](https://github.com/DarioSamo/libgens-sonicglvl), like the README.md mentions. They were like 3 line programs, using the LibGens::ARPack class in LibGens library. I don't have the source for those but you could easily recreate them.

**Comment by Auxy6858** [comment]
Thanks, I'm writing a C# library to interact with the files and this saves me reinventing the wheel.
