### ISSUE TITLE
Turing Fixer crashing due to ucrtbase.dll

### ISSUE THREAD

**Issue by cheatfreak47** [blueskythlikesclouds/SkythTools#3]
I tried to use turing fixer to fix the Wave Ocean mod and I kept getting this crash. 
```
Description
Faulting application name: TuringFixer.exe, version: 0.0.0.0, time stamp: 0x5e2b0b59
Faulting module name: ucrtbase.dll, version: 10.0.19041.423, time stamp: 0xccf6a09c
Exception code: 0xc0000409
Fault offset: 0x000000000007284e
Faulting process id: 0x2de0
Faulting application start time: 0x01d6751f7724fff6
Faulting application path: H:\SteamLibrary\steamapps\common\Sonic Generations\Turing\TuringFixer.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: d34f7e8f-a141-4d64-941b-dc0bd92580ee
Faulting package full name: 
Faulting package-relative application ID: 
```
Looking up the module seems to suggest its something that could be corrected by the developer so I figured I'd report it.
 https://superuser.com/questions/1397010/application-crash-due-to-ucrtbase-dll

**Comment by cheatfreak47** [comment]
note that users experiencing this crash can simply install the [windows 10 sdk 26624](http://download.microsoft.com/download/E/1/F/E1F1E61E-F3C6-4420-A916-FB7C47FBC89E/standalonesdk/sdksetup.exe) with just the windows 10 sdk checked during the install to fix this

still though, leaving this open because the tool ought to be recompiled to fix the issue if possible since I can see a lot of people with GTX 1650s and RTX 2060s and above are gonna have this problem keep popping up when trying to play old mods

**Comment by blueskythlikesclouds** [comment]
Hey, is this still a problem?

**Comment by blueskythlikesclouds** [comment]
I guess not.
