### ISSUE TITLE
Stuck when converting .eno models from sonic free riders

### ISSUE THREAD

**Issue by DatTaiwanGuy** [blueskythlikesclouds/SkythTools#4]
Hi, i tried this tool to unpack pac files from Sonic Free Riders https://github.com/Argx2121/Sega_NN_tools/releases/tag/0.7.0 but when i tried to convert one single .eno file from the stages folder, it just hangs.

Can you make this tool convert .eno files from some stages and also characters from Sonic Free Riders?

**Comment by blueskythlikesclouds** [comment]
Sorry? I'm not the creator of this tool you are talking about. Wouldn't it make more sense to ask there?

**Comment by Argx2121** [comment]
This been resolved for a long time. Feel free to delete / close this issue since it shouldn't of been posted here anyway
