### ISSUE TITLE
PackCpk error

### ISSUE THREAD

**Issue by auranderg** [blueskythlikesclouds/SkythTools#5]
No matter which cpk file I use, I get this error while trying to use PackCpk.exe:
```

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'CpkMaker.dll' or one of its dependencies. The specified module could not be found.
   at PackCpk.Program.Main(String[] args)

```
Am I missing something? This file seems to work perfectly fine for others

**Comment by Sajidur78** [comment]
You're missing CpkMaker.dll, it needs to be next to the exe.

https://github.com/blueskythlikesclouds/SkythTools/blob/master/Common/CpkMaker.dll

**Comment by auranderg** [comment]
> 
> 
> You're missing CpkMaker.dll, it needs to be next to the exe.
> 
> https://github.com/blueskythlikesclouds/SkythTools/blob/master/Common/CpkMaker.dll

Its already in there though. I downloaded the file again and replaced it just to see if the original dll was corrupted, but I'm still getting the error

**Comment by threethan** [comment]
Having this issue as well - seems to be caused by newer builds of Windows 11

EDIT: Never mind, installing VC redist for 2005-2015 fixed it. Most people will probably have them installed already, as a ton of games require them

**Comment by auranderg** [comment]
> 
> 
> Having this issue as well - seems to be caused by newer builds of Windows 11
> 
> EDIT: Never mind, installing VC redist for 2005-2015 fixed it. Most people will probably have them installed already, as a ton of games require them

You are a life saver, thank you
