### ISSUE TITLE
I can't open the Xno Converter 

### ISSUE THREAD

**Issue by DavidKK17** [blueskythlikesclouds/SkythTools#6]
Hello, I have a problem I can't open the Xno Converter because of a missing plugin. In the readme file it says that I need to install the .dll files in the "(Os root\Qt\5.5\msvc2010\plugins\platform". But I could'nt find such files, are QT or msvc2010 programs that I need to download? I 
would be grateful if you can help me.

**Comment by blueskythlikesclouds** [comment]
You need to copy the DLL file in the platforms folder to that directory.

**Comment by DavidKK17** [comment]
Yes, I know that's not the problem. I can't find the platforms folder because I don't have QT folder and msvc2010 folder. Are these programs that I need?

**Comment by blueskythlikesclouds** [comment]
You don't need to download any of these programs, create the folders exactly like the path given in the README and put the DLL file there.
