### ISSUE TITLE
ShadowModelConverter crashes and won't convert fbx file.

### ISSUE THREAD

**Issue by JCThornton90** [blueskythlikesclouds/SkythTools#8]
Hello! I've been having a go at modding Sonic Lost World with Model swapping Sonic, but I ran into a problem.
When I try to convert the chr_Sonic.fbx file by dragging and dropping it into the ShadowModelConverter.exe, it always crashed in the next second and fails to convert the model into the .shadow model format. 
I've also tried to run it as Administrator, but nothing worked either. Is there a solution to this? Let me know ASAP.
Thank you!

**Comment by blueskythlikesclouds** [comment]
It doesn't end with only giving it the .FBX file. You also need to provide the corresponding .model file as an input. This means you need to use the tool in CMD, like so:

`ShadowModelConverter chr_Sonic_shadow_model.fbx chr_Sonic.model chr_Sonic.shadow-model`

**Comment by JCThornton90** [comment]
> 

Much appreciated for the response and the helpful information!
I've done the required steps, and it came up as an error, saying that the required .dll file hostfxr.dll isn't found, and provided me a link to the required net core.
When I installed it, and got the DLL file and placed the file into the same directory, another error comes up saying that hostfxr.dll does not support single-file apps.
  _ To run this application, you need to install a newer version of .NET Core. with the same link I've already downloaded and installed. Am I doing something wrong? Let me know ASAP. Thank you. :)

**Comment by JCThornton90** [comment]
Never mind, I've found the solution. I've had to install the latest .NET Desktop Runtime, and then extract thehostfxr.dll file into the same directory of the Model converter, did it again, and it converted the model successfully! It's all fine and good now! :)

**Comment by blueskythlikesclouds** [comment]
Okay it appears you need the .NET runtime now.
Install b-- oh okay.
